apiVersion: v1
kind: Secret
metadata:
  name: ic-server-secrets
  namespace: ic-monitoring
  labels:
    app.kubernetes.io/name: ic-server
    app.kubernetes.io/part-of: ic-monitoring
type: Opaque
stringData:
  DB_PASSWORD: "CHANGE_ME"
  IC_API_KEY: "CHANGE_ME"
